# Generated by Django 6.0.2 on 2026-04-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marketcontext',
            index=models.Index(fields=['stock_symbol', 'date'], name='dashboard_m_stock_s_a2219f_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketcontext',
            constraint=models.UniqueConstraint(fields=('date', 'stock_symbol'), name='unique_market_context_per_day'),
        ),
    ]
