# Generated by Django 6.0.2 on 2026-04-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_marketcontext_dashboard_m_stock_s_a2219f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketcontext',
            name='unique_market_context_per_day',
        ),
        migrations.RemoveIndex(
            model_name='marketcontext',
            name='dashboard_m_stock_s_a2219f_idx',
        ),
        migrations.AddField(
            model_name='marketcontext',
            name='context_slot',
            field=models.CharField(choices=[('MORNING_0910', '09:10 AM Global Pulse'), ('MIDDAY_1300', '01:00 PM Midday Check'), ('CLOSE_1500', '03:00 PM Closing Setup')], default='CLOSE_1500', max_length=20),
        ),
        migrations.AddIndex(
            model_name='marketcontext',
            index=models.Index(fields=['stock_symbol', 'date', 'context_slot'], name='dashboard_m_stock_s_a5bb80_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketcontext',
            constraint=models.UniqueConstraint(fields=('date', 'stock_symbol', 'context_slot'), name='unique_market_context_per_slot'),
        ),
    ]
